<a href="https://colab.research.google.com/github/swflora/django-todolist/blob/main/ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


# 데이터 불러오기

In [4]:

import pandas as pd

titanic_df = pd.read_csv("/content/drive/MyDrive/머신러닝/data/titanic_train.csv")
titanic_df.head(3)



PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

## 데이터 확인

In [5]:
# 변수 타입 확인
print(type(titanic_df))

<class 'pandas.core.frame.DataFrame'>


In [6]:
# shape메서드, 행과 열을 튜플 형태로 변환
print(titanic_df.shape)

(891, 12)


In [8]:
# null값, 칼럼 별 type 확인
# 갯수를 비교하여 Null값의 존재 예측
print(titanic_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None


In [9]:
# 각각 데이터 타입에 맞게 설정이 잘 되어 있는 지 확인
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

# 데이터 정의서를 통해 각 컬럼명이 무엇을 의미하는지 확인, data dictionary
## 데이터 정의서를 작성할 때 주의 필요
##  https://lightgbm.readthedocs.io/en/stable/Installation-Guide.html

In [13]:
# 수치 데이터만 확인
# Pclass를 확인하면 숫자 분포가 독특함
# Survived, Pclass는 수치로 기록이 되어 있긴 하나 분포가 독특해 확인 필요
# value가 1,2,3으로만 분포할 가능성 존재
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [14]:
# 데이터 정의서를 통해 숫자이긴 하나 숫자를 의미하는 것이 아님을 알 수 있음
# 객실 등급을 의미함
titanic_df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [15]:
# 데이터 타입과 시리즈는 다른 타입
type(titanic_df['Pclass'])

pandas.core.series.Series

In [18]:
temp = titanic_df['Pclass'].value_counts()
print(temp.index)
print(temp)

Int64Index([3, 1, 2], dtype='int64')
3    491
1    216
2    184
Name: Pclass, dtype: int64


In [19]:
# 개수만 뽑는 방법
temp.values

array([491, 216, 184])

In [20]:
# value_counts를 사용할 때 null값을 무시하고 값을 내놓는 것에 주의
print(titanic_df['Cabin'].value_counts())

B96 B98        4
G6             4
C23 C25 C27    4
C22 C26        3
F33            3
              ..
E34            1
C7             1
C54            1
E36            1
C148           1
Name: Cabin, Length: 147, dtype: int64

In [22]:
# 결측치를 포함시켜서 출력하기
# 결측치 687개
titanic_df['Cabin'].value_counts(dropna = False)

NaN            687
C23 C25 C27      4
G6               4
B96 B98          4
C22 C26          3
              ... 
E34              1
C7               1
C54              1
E36              1
C148             1
Name: Cabin, Length: 148, dtype: int64

# 교재 p.50 - 53
- numpy, list, dictionary와 DataFrame으로 상호 변환이 가능하다.

In [23]:
# numpy로 변환
titanic_df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [24]:
# 리스트로 변환
titanic_df.values.tolist()

[[1,
  0,
  3,
  'Braund, Mr. Owen Harris',
  'male',
  22.0,
  1,
  0,
  'A/5 21171',
  7.25,
  nan,
  'S'],
 [2,
  1,
  1,
  'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'female',
  38.0,
  1,
  0,
  'PC 17599',
  71.2833,
  'C85',
  'C'],
 [3,
  1,
  3,
  'Heikkinen, Miss. Laina',
  'female',
  26.0,
  0,
  0,
  'STON/O2. 3101282',
  7.925,
  nan,
  'S'],
 [4,
  1,
  1,
  'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
  'female',
  35.0,
  1,
  0,
  '113803',
  53.1,
  'C123',
  'S'],
 [5,
  0,
  3,
  'Allen, Mr. William Henry',
  'male',
  35.0,
  0,
  0,
  '373450',
  8.05,
  nan,
  'S'],
 [6, 0, 3, 'Moran, Mr. James', 'male', nan, 0, 0, '330877', 8.4583, nan, 'Q'],
 [7,
  0,
  1,
  'McCarthy, Mr. Timothy J',
  'male',
  54.0,
  0,
  0,
  '17463',
  51.8625,
  'E46',
  'S'],
 [8,
  0,
  3,
  'Palsson, Master. Gosta Leonard',
  'male',
  2.0,
  3,
  1,
  '349909',
  21.075,
  nan,
  'S'],
 [9,
  1,
  3,
  'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
  'female',

In [26]:
# 데이터 프레임을 딕셔너리로 변환
titanic_df.todict('list')

# DataFrame의 칼럼 데이터 세트 생성과 수정

In [ ]:
data['새로운칼럼명'] = 연산

# 특정 칼럼을 삭제하고 싶을 경우
- axis = 1 -> 지정된 칼럼을 삭제
- axis = 0 -> 지정된 index(=행)을 삭제
- p.57 inplace = True 권장하지는 않음 -> 코드 실행 시 자동 업데이트
- 보통 temp2 = temp로 저장하지만 inplace을 작성할 경우, 오류가 생길 수 있음


# set_option()
# pandas 설정
- streamlit을 활용하여 테이블을 보여주고 싶을 경우엔 활용가치가 있지만
- 분석할 경우는 모호함
- data_editor()를 통해 설정하는 것이 좋음

# 데이터 셀렉션 및 필터링
- 데이터 연산을 위해 필요
- 방법은 여러가지가 있으나 loc 문법만 잘 기억해도 큰 문제가 되지 않음
- keyError -> 해당 데이터 프레임의 칼럼명이 현재 존재하지 않는 상태 or Dictionary의 Key값이 존재 하지 않는 상태


# 결손 데이터 처리하기
- Missing Data

In [9]:
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0        False     False   False  False  False  False  False  False   False   
1        False     False   False  False  False  False  False  False   False   
2        False     False   False  False  False  False  False  False   False   

    Fare  Cabin  Embarked  
0  False  False     False  
1  False  False     False  
2  False  False     False

## fillna()로 결손 데이터 대체하기

In [7]:
# p.78
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
# 문자 데이터를 가지고 할 때 강제로 'S'를 줄 수도 있지만 'S'를 넣은 이유는 S가 제일 많기 때문에

In [11]:
print(titanic_df['Embarked'].value_counts())
# 이런 방식으로 'S'가 아니라 코드를 작성해 넣을 수도 있음
print(titanic_df['Embarked'].value_counts().index[0])

S    646
C    168
Q     77
Name: Embarked, dtype: int64
S


In [12]:
# 가장 빈도수가 높은 index를 뽑는 방법도 있음
titanic_df['Embarked'].mode()

0    S
Name: Embarked, dtype: object

In [8]:
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

# apply lambda 식으로 데이터 가공
- lambda : 1회성 사용자 정의 함수, 간단한 연산을 처리할 때 사용

In [16]:
def get_square(a):
  return a ** 2

get_square(8)

64

In [18]:
# lambda 사용
lambda_square = lambda x : x ** 2
lambda_square(6)

36

In [20]:
# lambda 활용
a = [1,2,3,4,5,6]
squares = map(lambda x : x ** 2, a)
list(squares)

[1, 4, 9, 16, 25, 36]

In [22]:
# map 대신 apply를 사용하고 lambda를 사용
# 각 행 단위의 연산을 처리할 때 apply를 사용
# 반복문을 사용하지 않고 pandas의 경우, 메서드를 통해 구현 가능
# 짧은 연산의 경우는 lambda가 유용하지만 긴 코드 작성 시에는 사용자 정의 함수를 만드는 것이 좋음
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x : len(x))
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Name_len  
0      0         A/5 21171   7.2500  C000        S        23  
1      0          PC 17599  71.2833   C85        C        51  
2      0  STON/O2. 3101282   7.9250  C000        S        22

## apply()
- 행 단위로 연산을 할 때, apply()를 사용
  + lambda : 간단한 연산을 할 때는 lambda
  + udf(사용자 정의 함수) : if 조건절이 여러 번 사용될 것 같은 상황

In [23]:
def get_category(age):
    cat = ''
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else : cat = 'Elderly'

    return cat

In [25]:
# lambda 처리가 어려울 경우, 사용자 정의 함수를 만들고 lambda로 처리한다.
# 새로운 칼럼 생성
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df['Age_cat']

0          Student
1            Adult
2      Young Adult
3      Young Adult
4      Young Adult
          ...     
886    Young Adult
887        Student
888    Young Adult
889    Young Adult
890    Young Adult
Name: Age_cat, Length: 891, dtype: object

# 사이킷런(Scikit-Learn)
- Python 머신러닝 라이브러리
- 가장 유명하고 가장 대중적인 라이브러리 중 하나
- 엑셀 데이터(정형 데이터)를 사용한다면 머신러닝 디폴트 라이브러리
  +  최근 텐서플로, 캐라스, 파이토치 등 딥러닝 전문 라이브러리가 등장하면서 비정형데이터에선 잘 사용하진 않음, 위 세가지 예시는 정형데이터에 사용하긴 하지만 잘 사용하진 않음(해석의 어려움이 있기에)
  + 이미지(비디오, 영상), 자연어(텍스트 데이터)엔 사용하지 않음
- python기반의 다른 머신러닝 패키지도 사이킷런 스타일의 API를 지향
  + XGBoost, LightGBM, CatBoost 이런 종류의 알고리즘은 사이킷런 라이브러리 알고리즘이 아님
  + But, 위 알고리즘도 마치 사이킷런 클래스처럼 사용이 가능하도록 지원을 함

- 가장 큰 단점 중 하나는
  + 현재 GPU 연산을 하지 못하고 CPU연산만 가능함
  + XGBoost, LightGBM, CatBoost 라이브러리는 자체적으로 GPU연산을 지원함
  


In [28]:
import sklearn

sklearn.__version__

'1.2.2'

# 붓꽃 품종 예측하기
- 3가지 중 한개를 예측

In [29]:
# 필요한 모듈 불러오기
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


In [39]:
# 데이터 프레임 생성 목적
# seaborn에서 불러오는 거랑 차이점 존재
import pandas as pd

# numpy 배열로 데이터가 존재
iris = load_iris()

# 독립변수 = 설명변수
# 딕셔너리 key값만 출력
iris_data = iris.data


# 지도학습 = 종속변수
# 0dms setosa, 1은 versicolor, 2는 virginica 품종을 의미
iris_label = iris.target
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [33]:
import seaborn as sns

# seaborn 데이터는 species가 텍스트로 출력
# sklearn과 seaborn이 데이터를 불러오는 방식이 차이가 존재함
# sklearn은 바로 머신러닝 모델을 만들어야 하기에 텍스트가 존재할 수 없음
iris2 = sns.load_dataset("iris")
iris2

In [38]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 생각해야 할 점
- 종속 변수(target)가 문자로 되어 있다면, 수단과 방법을 가리지 않고 종속변수를 숫자로 변형해야함


In [40]:
# feature_names : 독립변수의 컬럼명
# 첫번째로 수행해야할 것 : 모든 데이터를 숫자로 변형
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)
iris['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

## train data와 test data로 분리
- 훈련/ 검증/ 테스트 데이터로 분리하는 것이 정석


In [46]:
# X_train : 훈련 데이터의 독립변수(설명변수)
# X_test : 테스트 데이터의 독립변수
# y_train : 훈련 데이터의 종속 변수
# y_test : 테스트 데이터의 종속 변수

# iris_data : 전체 데이터 독립 변수
# iris_label : 전체 데이처 종속 변수
# random_state : 뒤에 숫자는 의미 없음, 숫자가 만들어가면 됨
# 실행할 때마다 결과가 바뀌면 안되기에 조건을 동일하게 만들어 줌
X_train, X_test, y_train, y_test = train_test_split(iris_data,
                                                    iris_label,
                                                    test_size = 0.2,
                                                    random_state=11)


# 모델 학습
- DecisionTreeClassifier 객체 생성

In [47]:
dt_clf = DecisionTreeClassifier(random_state = 11)
# random_state는 고정

# 학습 수행
dt_clf.fit(X_train, y_train) # 훈련 데이터의 독립 변수, 종속 변수


DecisionTreeClassifier(random_state=11)

# 예측
- 테스트 데이터 세트로 예측 수행

In [49]:
# p. 90
# 테스트 데이터의 독립 변수만 예측
pred = dt_clf.predict(X_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [51]:
# X_test의 예측과 비교하여 정확도를 알기 위해 y_test 사용
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [52]:
# 정확도 확인
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9333333333333333

# 사이킷런의 코드 형식
- sklearn.pipeline 방식대로 작성하는 것을 매우 강력하게 추천
  + 빅데이터 분석기사 : 머신 러닝 관련된 시험(40점 만점)

- 수많은 머신러닝 교재를 사용해도 pipeline을 잘 소개하는 책은 거의 X
  + 빅데이터 분석기사 교재는 전무


# Model Selection 모듈 소개

In [53]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

# 학습 데이터 셋으로 예측 수행
pred = dt_clf.predict(train_data)
print('예측 정확도:',accuracy_score(train_label,pred))

# 예측이 정확히 100%되는 것은 말이 되지 않음
# 아래 결과가 100% 정확한 이유는 이미 학습한 데이터셋을 기반으로 예측했기 때문

예측 정확도: 1.0


- 답을 알고 있는 상태에서 문제를 풀었다는 것을 의미
- 그렇기에 훈련데이터와 테스트 데이터를 분리하는 것.

In [55]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier( )
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,
                                                    test_size=0.3, random_state=121)

dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9556


-  교차검증을 하는 이유는 이론적으로는 과적합, 현실적으론 데이터 수집이 어렵기에 수행
# K-폴드 교차 검증
- k=5인 경우에는, 5번의 모델 학습을 수행
  + 훈련 데이터와 검증 데이터의 샘플은 각각 다름
  + 평가 5번을 통해 평균을 뽑는 것이 목적 -> 안정적으로 사용하기 위해


In [56]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성.
# 리스트를 생성한 것을 반복문을 쓰겠다는 의미와 같음
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:',features.shape[0])


붓꽃 데이터 세트 크기: 150


In [57]:
n_iter = 0

# features는 독립 변수, label은 종속 변수
# KFold객체의 split( ) 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index  in kfold.split(features):

    # kfold.split( )으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    #학습 및 예측
    dt_clf.fit(X_train , y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    # 반복 시 마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test,pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
          .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
    cv_accuracy.append(accuracy)
    # 인덱스가 순차적으로 잘림
    # 검증 정확도가 매 번 다름
    # 코드보다는 개념 이해가 중요, k-폴드의 코드 진행은 항상 같은 방식이 아님

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도 :1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 :0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 :0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 :0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 :0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


# ML 과정
- 데이터 수집
- 데이터셋 분리(중점)
  + 통계에서 말하는 샘플링 에러와 관련이 있음
- 모델 불러오기
- 모델 학습
- 모델 평가


# Stratified K 폴드
- 종속변수가 불균형한(imbalanced)분포도를 가진 데이터 집합
  + 코로나 데이터(양성/음성)
    - 검사 10만명, 양성 판정을 받는 사람은 매우 적고 / 대부분은 다 음성 판정을 받음
    - 전형적으로 결과가 불균형한 데이터셋
- 샘플링을 무작위로 수행한다면 불균형한 샘플을 얻을 수 밖에 없기에 비율에 따라 데이터셋을 뽑아야한다.


In [58]:
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

kfold = KFold(n_splits=3)
# kfold.split(X)는 폴드 세트를 3번 반복할 때마다 달라지는 학습/테스트 용 데이터 로우 인덱스 번호 반환.
n_iter =0
for train_index, test_index  in kfold.split(iris_df):
    n_iter += 1
    label_train= iris_df['label'].iloc[train_index]
    label_test= iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

    # 모든 label이 일정하게 뽑이지 않기에 k-폴드 방식은 사용할 수 없다

## 교차 검증: 1
학습 레이블 데이터 분포:
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


In [59]:
# 층화추출 방식으로 데이터셋 분리
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train= iris_df['label'].iloc[train_index]
    label_test= iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

# 매 번 모든 label 비율이 일정하게 나옴

## 교차 검증: 1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [60]:
dt_clf = DecisionTreeClassifier(random_state=156)
skfold = StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

# StratifiedKFold의 split( ) 호출시 반드시 레이블 데이터 셋도 추가 입력 필요
for train_index, test_index  in skfold.split(features, label):
    # split( )으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    #학습 및 예측
    dt_clf.fit(X_train , y_train)
    pred = dt_clf.predict(X_test)
    # 반복 시 마다 정확도 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
          .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
    cv_accuracy.append(accuracy)

# 교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:', np.round(np.mean(cv_accuracy), 4))

# 어떻게 데이터셋을 분리하던지 정확도가 비교적 일정하게 유지됨 = 모델의 일반화
# 모델을 안정적으로 개발했다고 함



#1 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 :0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9667
